### ISSUE TITLE
Release paper experiment generation code

### ISSUE THREAD

**Issue by vivi** [cpacker/MemGPT#103]
We will work on polishing up the paper eval code and preparing it for release.

Roughly, you can replicate our results by doing the following:

* Download the MSC_self_instruct and wikipedia_embeddings from our [Hugging Face repo](https://huggingface.co/MemGPT).

Example (pseudo-ish) code for generating MSC openers:
```text
read in self_instruct_data
for every dialogue session in self_instruct_data:
    feed dialogue to memgpt
    instruct memgpt to generate a session opener
        login_msg['type'] = 'login (returning user)'
        login_msg['type'] = 'login (provide a friendly personalized greeting)'
compute csim-1, csim-3, csim-h
```

For Wikipedia Doc QA:
Based off https://github.com/nelson-liu/lost-in-the-middle -- we use their dataset (nq-open-oracle.jsonl.gz)
```text
load in wikipedia embeddings
for every question in first N samples:
    ask memgpt question
```

FYI, these results are quite expensive and resource-intensive to replicate, we will work on releasing the MemGPT generations from our paper.

**Comment by vivi** [comment]
Function traces from our experiments are here: 

https://huggingface.co/datasets/MemGPT/function-call-traces

**Comment by HelloWorld4747** [comment]
> We will work on polishing up the paper eval code and preparing it for release.
> 
> Roughly, you can replicate our results by doing the following:
> 
>     * Download the MSC_self_instruct and wikipedia_embeddings from our [Hugging Face repo](https://huggingface.co/MemGPT).
> 
> 
> Example (pseudo-ish) code for generating MSC openers:
> 
> ```
> read in self_instruct_data
> for every dialogue session in self_instruct_data:
>     feed dialogue to memgpt
>     instruct memgpt to generate a session opener
>         login_msg['type'] = 'login (returning user)'
>         login_msg['type'] = 'login (provide a friendly personalized greeting)'
> compute csim-1, csim-3, csim-h
> ```
> 
> For Wikipedia Doc QA: Based off https://github.com/nelson-liu/lost-in-the-middle -- we use their dataset (nq-open-oracle.jsonl.gz)
> 
> ```
> load in wikipedia embeddings
> for every question in first N samples:
>     ask memgpt question
> ```
> 
> FYI, these results are quite expensive and resource-intensive to replicate, we will work on releasing the MemGPT generations from our paper.

Hello,
I am still pretty struggling with how to write code for evaluating the MemGPT's response on the deep memory retrieval task. I fully understood it may be quite expensive to re-generate all the experimental results again. But, could you please go through one detailed example so that I can follow? What I mean is you don't need to generate the result. You can just tell me step by step, for example,
Step 1: load the MSC dataset (currently how i load my dataset is using the command 'memgpt load directory ... ', but i dont know if i should follow the same step for the evaluation process)
Step 2: feed the question to memgpt (i am so confused about how you execute this step since I only know running the memgpt locally. Does this mean I have to enter all the questions manually? Surely, I am wrong but I dont know how to solve this question.)
...

Appreciate all your help! Looking forward to your response soon!

**Comment by hy522** [comment]
Hi follow up on this, currently there're only Nested K/V and Document Q/A code in the repo, any plan to release DEEP MEMORY RETRIEVAL TASK and CONVERSATION OPENER TASK eval code?
