### ISSUE TITLE
Keep hitting openai rate limit

### ISSUE THREAD

**Issue by SingL3** [cpacker/MemGPT#125]
Hi, currently the `memgpt` is the only app doing requests to openai and it keep raising this and `Thinking`:
```
acreate (backoff): caught error: Rate limit reached for gpt-4 in organization org-uL6ErIyeknQXybIzTsylefqn on tokens per min. Limit: 10000 / min. Please try again in 6ms. Contact us
through our help center at help.openai.com if you continue to have issues.
```

Is there any limit for the doc or something? The length of the doc or whatever?

**Comment by SingL3** [comment]
After 20 retries, I got this:
```
openai.error.RateLimitError: Rate limit reached for gpt-4 in organization org-uL6ErIyeknQXybIzTsylefqn on tokens per min. Limit: 10000 / min. Please try again in 6ms. Contact us through our help center at help.openai.com if you continue to have issues.
```
So maybe I need to shorten my doc？

**Comment by SingL3** [comment]
@tractorjuice I am the only user of my openai account, so I am confused about this. That means the `Memgpt` itself hit the rate limit.

**Comment by tractorjuice** [comment]
> @tractorjuice I am the only user of my openai account, so I am confused about this. That means the `Memgpt` itself hit the rate limit.

Or you have a very small quota for API calls. Check your limits.

Due to the MemGPT architecture, it is hungry for API calls and tokens 😁.

**Comment by tractorjuice** [comment]
> > @tractorjuice I am the only user of my openai account, so I am confused about this. That means the `Memgpt` itself hit the rate limit.
> 
> Or you have a very small quota for API calls. Check your limits.
> 
> Due to the MemGPT architecture, it is hungry for API calls and tokens 😁.

Sign up to PromptLayer and push the API calls through there. You will see every single call in detail + latency.

**Comment by cpacker** [comment]
Are you completely sure you're the only one using that OpenAI API org?

If you go to https://platform.openai.com/account/usage, you can click down into "Daily Usage" and see the exact requests made and their timestamps.

MemGPT will launch requests of up to 8k tokens - I think most people have a 10k/min token limit on gpt-4, so this means that technically MemGPT can run only ~1-2 times per minute. However in practice, we've found that if you're the only person using an OpenAI API account with GPT-4 access, you shouldn't hit the rate limit that often (in fact MemGPT should feel quite smooth with minimal extended latency due to backoff on rate-limited requests).

If this problem is still affecting you and you've determined that (1) you have a token limit of 10k for gpt-4, (2) you are 100% the only person using the account as shown in the daily breakdown, please reopen the issue (and maybe DM us a screenshot of the usage on Discord, or post a full output of the MemGPT command you ran here on GitHub) and we will take a closer look!

**Comment by jms90h5** [comment]
After updating my install of pymemgpt and regenerating the archive I'm still getting rate limit errors.  Note that the queries do eventually succeed, although sometimes the generated messaged exceed the context limit.  Please see the attached screenshot.
<img width="1025" alt="Screenshot 2023-11-06 at 10 29 40 AM" src="https://github.com/cpacker/MemGPT/assets/6079892/7f712091-feef-4d3d-aaf6-0e7316361afa">
