### ISSUE TITLE
Docker image does not have "memgpt" command

### ISSUE THREAD

**Issue by dpkirchner** [cpacker/MemGPT#1383]
**Describe the bug**
The docs ask us to run `memgpt configure` and other command line scripts to interact with memgpt, however if you're using the `memgpt/memgpt-server:0.3.14` docker image you'll find there's no such command.

**Please describe your setup**
- [ ] How did you install memgpt?
  - https://github.com/cpacker/MemGPT/blob/main/compose.yaml followed by creating a .env file with PG creds and `docker-compose up -d`
- [ ] Describe your setup
  - WSL2, Docker

**Additional context**
There's no memgpt command:

```
root@memgpt-server:/# find / -name memgpt -type f
root@memgpt-server:/# find / -name memgpt.py -type f
root@memgpt-server:/#
```

The closest thing I can find is `/memgpt/cli/cli.py`, however I don't see a way to run it.

**Comment by sarahwooders** [comment]
Sorry this is unclear from the documentation - you need to install the CLI with `pip install pymemgpt` and then run `memgpt configure`. This creates a `~/.memgpt/config` file that can be linked in the container. It's a bit hacky right now since we are still working on improving the configuration for the container deployment.

**Comment by dpkirchner** [comment]
Ahh, thank you!
