### ISSUE TITLE
no wrapper for specified local LLM

### ISSUE THREAD

**Issue by iplayfast** [cpacker/MemGPT#153]
Trying out using https://www.youtube.com/watch?v=QCdQe8CdWV0&ab_channel=MatthewBerman as tutorial. 

using text-generation-webui to expose the LLM's api.
export OPENAI_API_BASE=http://127.0.0.1:5000
export BACKEND_TYPE=webui

python main.py --no_verify

Every text entry I do get's
Warning: no wrapper specified for local LLM, using the default wrapper
An empty text entry doesn't. 

I don't know what this means.

**Comment by v-kamelowy** [comment]
That'll be good to know. I saw in the files that there are wrappers for airoboros and dolphin, but haven't found a way to select one yet.

**Comment by iplayfast** [comment]
Hmm, it's occasionally crashing, I think due to this error. I'm using mistralai_Mistral-7B-v0.1 in text-generation-webui
I don't suppose there is a way to query the model name through the api?

**Comment by v-kamelowy** [comment]
It is probably crashing because you are using model that is not actually supported now and you get corrupted JSON responses.
I am using `dolphin-2.1-mistral-7b.Q8_0.gguf` _(https://huggingface.co/TheBloke/dolphin-2.1-mistral-7B-GGUF)_ and It is generating valid JSON, but sometimes it sends empty function calls
e.g.
```
⚡🧠 [function] updating memory with core_memory_append:
> Enter your message:
```

That's the beauty of cutting-edge tech, I guess 😅

**Comment by jackfood** [comment]
It just hang at here, what happened? i am using dolphin-2.1-mistral-7b.Q5_0.gguf.

![image](https://github.com/cpacker/MemGPT/assets/11504716/d31c6ba9-c2d7-45f6-b1d2-2440ee31ba3a)

**Comment by cpacker** [comment]
> That'll be good to know. I saw in the files that there are wrappers for airoboros and dolphin, but haven't found a way to select one yet.
> 
> EDIT:
> 
> ```python
> async def get_chat_completion(
>     model,  # no model, since the model is fixed to whatever you set in your own backend
>     messages,
>     functions,
>     function_call="auto",
> ):
>     if function_call != "auto":
>         raise ValueError(f"function_call == {function_call} not supported (auto only)")
> 
>     if model == "airoboros-l2-70b-2.1":
>         llm_wrapper = airoboros.Airoboros21InnerMonologueWrapper()
>     elif model == "dolphin-2.1-mistral-7b":
>         llm_wrapper = dolphin.Dolphin21MistralWrapper()
>     else:
>         # Warn the user that we're using the fallback
>         print(f"Warning: no wrapper specified for local LLM, using the default wrapper")
>         llm_wrapper = DEFAULT_WRAPPER
> ```
> 
> So, wrapper will always fallback to default wrapper (airoboros) because the variable "model" is not populated with your model name (as the comment says "no model, since the model is fixed to whatever you set in your own backend") and Warning will always be printed.

When you use local models (ie you set OPENAI_API_BASE and BACKEND_TYPE), `--model` takes on a different meaning - it no longer specifies the model you will run (because how could you control that anyways? in web UI / LM Studio, you load one model at a time and put it behind a "black box" IP address).

Instead, `--model` becomes the wrapper / prompt formatter that MemGPT will use when interfacing with the local LLMs behind your IP address / webserver. By default, it'll use the airoboros wrapper, but you can change it by just passing the wrapper name to `--model`.

**Comment by cpacker** [comment]
@jackfood your error seems unrelated to this issue, can you post it (if you're still running into it) on the discussion page?

Closing issue since this seems to be resolved (use `--model` if you don't want to get the warning message).

**Comment by Rivelyn** [comment]
Can someone clarify where to use the --model??

**Comment by cpacker** [comment]
@Rivelyn when using OpenAI API, --model will specify which OpenAI model gets selected, eg gpt-4, gpt-3.5-turbo, gpt-3.5-turbo-16k, etc.

When using your own LLM backend (`export OPENAI_API_BASE=...; export BACKEND_TYPE=webui`), --model specifies which prompt formatter is run on your model.

So if you set up MemGPT to run with a local LLM, say dolphin mistral running on web UI, if you pass in `--model airoboros-l2-70b-2.1` you are still running dolphin mistral (via web UI), but you're using the airoboros prompt format. `airoboros-l2-70b-2.1` is the default too, so if you don't include `--model`, you'll see a warning, but you can ignore it.

At the moment my personal recommendation is to always use the `airoboros-l2-70b-2.1` wrapper by default, and use the other one (or implement your own) if you want to experiment.
