### ISSUE TITLE
Consider using LangChain for all LLM calls.

### ISSUE THREAD

**Issue by tractorjuice** [cpacker/MemGPT#160]
Please take a look at LangChain.

https://python.langchain.com/docs/get_started/introduction

It can simplify the code, as LangChain has all the logic for dealing with API errors, integrations with other LLMs, etc.

For example, https://python.langchain.com/docs/guides/adapters/openai

**Comment by cpacker** [comment]
Copying from a discord message:

>the concepts in memgpt are both (1) simple enough that we didn't think it was a good idea to built it on top of a huge package like langchain (but you can definitely integrate it into langchain if you want!), (2) different enough from langchain's base abstractions (memgpt has a specific control flow with events->functions->yield) that overall we just decided it's better off to keep the code as simple as possible and build on ChatCompletion API as the foundation instead

Re: the adapters, we don't want to use OpenAI ChatCompletion adapters because they don't handle function calling. More discussion on that here: https://github.com/cpacker/MemGPT/tree/main/memgpt/local_llm#status-of-chatcompletion-w-function-calling-and-open-llms.

Re: API errors, if there's API error catching code you think we should port from langchain happy to take a look and possibly port over individual components (however I don't think it's a good idea to add a big dependency like that purely for API error catching code).
