### ISSUE TITLE
Discord Bot Memory Storage Question

### ISSUE THREAD

**Issue by gianni-dalerta** [cpacker/MemGPT#40]
Very interesting implementation... where is the data saved when conversing with the chatbot? how is memory handled in this implementation?

**Comment by cpacker** [comment]
To implement the discord bot, we subclass the archival and recall classes with new classes that use databases (eg MongoDB) to store the persistent information, rather than a python list (which is turned to JSON when you `/save` in the CLI).

You don't need a lot of code to do this, but it does become very specific to your database of choice, which is why we only implemented in-memory data stores for the initial GitHub release. However we are planning on releasing some more examples, see #32. If you try to add one yourself in the meantime, feel free to comment on that thread and we can help you out with implementation if you get stuck.

Merging with #32

**Comment by goetzrobin** [comment]
@cpacker Thanks for sharing this and making the code open source! 

This work is incredible and has me very excited to learn more about it (and hopefully be able to contribute at some point.) I was curious about the functioning of the discord bot, too. 

Since this is not really specific to the archival & recall stores, but more a question of general understanding, I will ask the question here instead of #32.

How is it possible that "my" agent always also has "my" memory and is not leaking other people's "memories"?

I'll lay out my theory of how this could work, but I hope you can correct me or tell me I am completely off if that is the case... 

- I assume that the discord bot communicates to some version of a web API.
- In today's backend web world, most APIs are "stateless". 
- Based on that assumption, we would need **recall** the latest version of the "working memory" for every request, execute our request, and then **archive** it to a persistent storage again.
- That way a single server can service multiple users at the same time...

Is this along the lines of how the discord bot operates or am I completely missing the mark here?

Thanks again for all your work and sharing this with us!

Have a great night!

**Comment by cpacker** [comment]
Even though we store everything on a single database, it's all indexed with unique user IDs (every agent, memory, message, etc. is tied to specific user), so there's no possibility of mixing of memories or agents between users.

**Comment by goetzrobin** [comment]
Thanks for letting me know. That is what I thought! 👍 So if I am following correctly, there is only one instance of (the works with discord version) MemGPT running at the same time?

Sorry to bother you with all these "implementation details" questions, but I am absolutely amazed by the idea of having multiple distinct agents and memories that I can access through a single interface, which means the Discord bot is exactly what I am trying to recreate locally.

**Comment by cpacker** [comment]
You can definitely implement this different ways - have many copies of the code running, one per person, or have one copy of the code running, with multiple agents objects. Both can work for implementing a type of bot service.
