### ISSUE TITLE
AttributeError: 'Agent' object has no attribute 'context_window'

### ISSUE THREAD

**Issue by xhrt** [cpacker/MemGPT#515]
**Describe the bug**
I run "python main.py" in MemGPT.When I want to begin the conversation,the error occured "AttributeError: 'Agent' object has no attribute 'context_window'".
Could you please tell me how to solve this problem.
I can use"memgpt run"to start a conversation successfully.But I find that use "python main.py"can print more information,such as prompt,core memory and so on.So I' rather use "python main.py".

**Comment by cpacker** [comment]
@xhrt since it seems like you've installed MemGPT from source, can you get the latest code (`git pull`), rerun `memgpt configure` then `memgpt run` and confirm if you're still having this problem?

`python main.py` has been deprecated and is no longer supported, and I don't think this error should occur with the regular workflow. I'm going to close this issue for now but please reopen this PR if you're still having problems (or ping us on the Discord #support channel).
