### ISSUE TITLE
MemGPT AutoGen agent load/save

### ISSUE THREAD

**Issue by cpacker** [cpacker/MemGPT#600]
**Is your feature request related to a problem? Please describe.**

Add a load/save to the MemGPT AutoGen integration to allow users to link existing MemGPT agents into AutoGen scripts

Can use the same style of code as the internal server API loading of existing agents (the API calls take an agent_id as input): https://github.com/cpacker/MemGPT/blob/server-refactor/memgpt/server/server.py#L106-L124

**Comment by hemanthsavasere** [comment]
I would like to work on this issue, if possible can this issue be assigned to me.

**Comment by RonABarrett** [comment]
The following code defines a function for loading pre-existing agents.  The function has a hard-coded agent_confi_path prefix (i.e. "C:\\Users\\Owner\\.memgpt\\agents\\") and is appended with {agent_name}.  The function returns three attributes: 'client', 'agent_id', and 'agent_config'.

For example purposes two agents are loaded: Memgpt_strategist, Memgpt_critic.

CODE:
from memgpt.config import AgentConfig
from memgpt import MemGPT
from memgpt.interface import CLIInterface as interface
from memgpt.constants import MEMGPT_DIR

def load_agent(agent_name):
    # Load existing agent configuration
    agent_config_path = f"C:\\Users\\Owner\\.memgpt\\agents\\{agent_name}\\"
    agent_config = AgentConfig.load(agent_config_path)
    skip_verify = agent_config.model != "gpt-4"

    # Convert AgentConfig object to dictionary
    agent_config_dict = agent_config.__dict__

    client = MemGPT(
        auto_save=True,
        quickstart=None,
        config=agent_config_dict
    )

    # Load existing agent
    agent = client.create_agent(agent_config=agent_config)

    return {
        'client': client,
        'agent_id': agent,
        'agent_config': agent_config
    }

# Use the function to load the agents
Memgpt_strategist = load_agent("Memgpt_strategist")
Memgpt_critic = load_agent("Memgpt_critic")
#=============================
"""
    you can access the client, agent, and agent configuration of each agent using the keys of the dictionary:
    client_01 = Memgpt_strategist['client']
    agent_01 = Memgpt_strategist['agent_id']
    agent_config_01 = Memgpt_strategist['agent_config']

    client_02 = Memgpt_critic['client']
    agent_02 = Memgpt_critic['agent_id']
    agent_config_02 = Memgpt_critic['agent_config']

    Or directly:
    print(Memgpt_strategist['agent_config'].name)
"""

**Comment by nickknyc** [comment]
@RonABarrett thanks so much for the code provided - I am running into some issues and I am no where nearly familiar enough with the code to venture a fix. Here is what I am finding with pylint. Any help would be greatly appreciated.

`from memgpt.interface import MemGPT `
E0602: Undefined variable 'MemGPT' (undefined-variable)

was also having some issues with termination here
`agent_config_path = f"C:\Users\Owner\.memgpt\agents\{agent_name}\"`
this seems to work as far as the VSCode debugger is concerned
`agent_config_path = f"C:\Users\Owner\.memgpt\agents\{agent_name}"`

**Comment by RonABarrett** [comment]
Hi Nick!
The Memgpt unknown variable is popping up. This could be due to not having
the most recent updates from the Github repository.   CPacker and others
made some updates specifically for Python programmers.
A suggestion is to:
1. Locate where your memgpt application code folder are.
2. Backup
3. Copy the Github files for a fresh install.

Let me know if I can help.

Cheers,
Ron

**Comment by nickknyc** [comment]
per my discord message to Charles

@cpacker - I made the move to 0.2.11 and that cleared the initial issue. Now I am struggling with WHERE the agent configs  are being stored.

I would like them to reside wherever I like - preferably a folder that is mounted to the dev container so I can use them in multiple projects. 

presently whatever I set in this line  - per the code in 600
`agent_config_path = f"C:\Users\Owner\.memgpt\agents\{agent_name}\"`
the system is appending that to the existing memgpt base path... so I get something that looks like this 

Here I want to use a folder inside my AutoGen project
`agent_config_path = f"./s13/agents/{agent_name}"`
when I run I get an error ... 
`Agent config file does not exist at /home/vscode/.memgpt/agents/./s13/agents/Memgpt_strategist/config.json
`
Thanks in advance
![image](https://github.com/cpacker/MemGPT/assets/1598572/93d9d4d0-595c-4a4d-a449-90f2752970f0)

**Comment by RonABarrett** [comment]
Hmmm... I would hesitate to seek putting an agent config file wherever you
want.  There's too much presumed within the code base (e.g. where the
agent_state files are stored.)  The code assumes agents, personal, humans,
etc. are sub-folders off of .memgpt folder.

On my installation, these folders are under:
C:\\Users\\Owner\\.memgpt

**Comment by RonABarrett** [comment]
Also, have you set the agent_name to the name of an existing agent on
your end?  'Memgpt_strategist' is the name of an agent I created.

**Comment by RonABarrett** [comment]
Nick,
In the following section of code that I initially sent there are two agents loaded via the function.  The two agent names are: Memgpt_strategist and Memgpt_critic.  If you simply copied/pasted the code I shared, it will throw an error trying to load Memgpt_strategist because the agent doesn't exist on your system

Use the function to load the agents
Memgpt_strategist = load_agent("Memgpt_strategist")   # <--------- Is this where your error is being caused??
Memgpt_critic = load_agent("Memgpt_critic")
#=============================
"""
you can access the client, agent, and agent configuration of each agent using the keys of the dictionary:
client_01 = Memgpt_strategist['client']
agent_01 = Memgpt_strategist['agent_id']
agent_config_01 = Memgpt_strategist['agent_config']

client_02 = Memgpt_critic['client']
agent_02 = Memgpt_critic['agent_id']
agent_config_02 = Memgpt_critic['agent_config']

Or directly:
print(Memgpt_strategist['agent_config'].name)

**Comment by nickknyc** [comment]
@RonABarrett thanks so much for pointing out where they sit on disk, in Windows, when using a Docker Dev Container... yeesh.. 

OK - I can work with that, though I would love to see that as something you have a bit more control over when setting up. 

Next question then... if I am using ChromaDB, rather than local... then what? Looking in the same directory there should be a Config Folder with Chroma folder in there, if I am reading things correctly during configure... 

```
Enter persistent storage location: /home/vscode/.memgpt/config/c
hroma
📖 Saving config to /home/vscode/.memgpt/config
```
But I don't see anything - and I am selecting Persistent..

**Comment by RonABarrett** [comment]
Hmmm... that I don't have knowledge to guide you on.

Coming back to revising the code I share with you earlier, did you modify line 30, Memgpt_strategist = load_agent("Memgpt_strategist"), with the name of an existing agent?  By that question I mean say you have an agent named, agent_1, then the line of code would be, Agent_1 = load_agent("agent_1").  Of course, rather than 'Agent_1' you could name it anything you want.  Just the string value inside the load_agent() function needs to be the name of an already existing agent under the .memgpt\\agents\\ folder.

**Comment by nickknyc** [comment]
are you saying i should first create the agents at the memgpt commandline?

ideally that would be part of the script if not found, offer to create..

thanks - getting there

Sent from Surface Duo
________________________________

**Comment by RonABarrett** [comment]
Yes, this code is specifically for loading an existing agent.

For creating an agent from within a python program take a look at the two program examples here on the Memgpt Python client page:  https://memgpt.readme.io/docs/python_client

**Comment by RonABarrett** [comment]
Nick, perhaps the attached file may be of help for you.  I went through all of the Memgpt files on Github and outlined some documentation.  The intent is to help readers understand search for a particular function, its purpose, etc.  To see the actual code you can simply navigate on Github to the actual program file.

[MemGPT_Packages_Classes_Functions_Other.pdf](https://github.com/cpacker/MemGPT/files/13845956/MemGPT_Packages_Classes_Functions_Other.pdf)

**Comment by nickknyc** [comment]
@RonABarrett - wow that is super helpful - hope it was tool generated ;^)

I now find myself sucked into setting up ChromaDB - want to be in client/server mode... getting all the docker stuff configured will take me a bit, I fear. Going to set it up in the same Docker container at first, but really want it in it's own.. 

```
 I am also happy to find this MEMGPT_CONFIG_PATH:
 export MEMGPT_CONFIG_PATH=/my/custom/path/config # make sure this is a file, not a directory
```
Which should help me keep everything where I need them. 
Will likely report back tomorrow.

Just for posterity, my goal is 

create a group of memgpt_agents that 
all store their data in ChromaDB and can then be 
deployed into various projects (autogen or not)
they will bring all their memory to every project and 
they will persist their memory from each project (task)
in time, some will become very experienced and expert in a given domain.
![Mission-Impossible-IMF-Dossier-Portfolio-1](https://github.com/cpacker/MemGPT/assets/1598572/8357bdd8-a335-4658-a14c-520f3cd59b7d)


agents aren't one and done, they require training and grooming and EXPERIENCE. ;^)

**Comment by RonABarrett** [comment]
I have done something very similar to what you're describing but with a
json file as the multi-agent conversation history file, rather than
Chromadb.

What I was challenged by:
1. OpenAI assistants via the API inconsistent in their ability to read
uploaded files or even files attached to them via the Assistants page on
OpenAI.com
2. Group chats have generated subpar content. I've set up a chat of eight
assistants. One off-topic response can derail the responses of following
assistants.

Group chats are a "breadth-first" approach to expert advice. Get everybody
in the room  let them talk, see what comes out of it. Like a mastermind
group.

I am now pursuing a "depth-first" approach. Presenting a topic to an
assistant.   Iterative provide prompt messages to have the assistant dive
deeper while gradually adding breadth.

The final outcome from each assistant can be submitted to a group chat for
comment.

**Comment by nickknyc** [comment]
very helpful info
file handling - you really need to have the data analysis tool do all that wprk and yeah i hear ypu on reliability.

looking forward to what i find... back to dockerland. and trying to get this all set up properly.

**Comment by RonABarrett** [comment]
Awesome, thanks for the update!
