### ISSUE TITLE
missing mkdocs.yml file "feat: Migrate docs #646 "

### ISSUE THREAD

**Issue by r3d91ll** [cpacker/MemGPT#662]
**Describe the bug**
It appears that the mkdocs.yml file was deleted during " feat: Migrate docs #646 ", The mkdocs now builds but does so incorrectly. see attached screenshot

**Please describe your setup**

- [ ] MemGPT version
  I noticed when I cloned a new dev instance
- [ ] How did you install memgpt?
  - Cloned and followed the steps as outlined in docs/contributing_code.md
- [ ] Describe your setup
  - Ubuntu 2004 workstation, running through VS Studio code terminal.
![Screenshot at 2023-12-20 13-02-32](https://github.com/cpacker/MemGPT/assets/4719235/5b04bc44-a3ad-4a24-8dcc-045f010179db)

**Screenshots**

**Additional context**

---

**Comment by cpacker** [comment]
Hi @r3d91ll - we actually migrated off of mkdocs+readthedocs to readme, and in doing so deprecated support for the mkdocs workflow (otherwise we'd have to start maintaining both the mkdocs index and the readme index). If you need a copy of the docs pre-migration you can check the `docs-checkpoint` branch.

AFAIK there's no easy way to build readme docs into a site locally which is an unfortunate downside of this migration (I think the "correct" way to do this is to set up your own readme project and use `rdme docs` to sync to your own site for viewing?). Closing for now since this deprecation is intended, but if you have any feedback on a good way to support local builds to html that doesn't require maintaining another index like w/ mkdocs happy to try and incorporate it.
