### ISSUE TITLE
`/load` fails on certain large files

### ISSUE THREAD

**Issue by cpacker** [cpacker/MemGPT#755]
**Describe the bug**

Certain large files trigger the following error:
```
memgpt/memgpt/embeddings.py", line 64, in _call_api
    raise TypeError(f"Got back an unexpected payload from text embedding function, response=\n{response_json}")
TypeError: Got back an unexpected payload from text embedding function, response=
{'message': 'Input validation error: `inputs` must have less than 512 tokens. Given: 628', 'code': 413, 'type': 'Validation'}
Generating embeddings:  53%|████████████████████████████▊                         | 5809/10866 [40:33<35:18,  2.39it/s]
```

Chunking size may be too large for the embedding.

**How to reproduce**

```sh
poetry run memgpt load directory --name code-gorilla-test --input-dir ~/dev/gorilla-cli --recursive
```

**Comment by jimlloyd** [comment]
This bug is happening for me with some C++ source files. In this case, the bug is that the `CodeSplitter` parser that is used for splitting source code has an API where the maximum number of _characters_  (`max_chars`) can be specified (default is 1500) but the `chunk_size` values used by other file parsers is ignored. We are using the high-level `ServiceContext.fromDefault() `method which sets up all of the various parsers semi-automatically. That function does not allow specifying `max_chars`. 

The bug was reported for ebook files (`.epub`). Parsing these files probably uses https://llamahub.ai/l/file-epub , the source code for which is here: https://github.com/run-llama/llama-hub/blob/8fa06e01f1ae72722cd77372fc1cf23e4ef37e08/llama_hub/file/epub/base.py

It looks like that epub reader converts the .epub to plain text and then returns it as a Document, so the plain text splitter probably has the last say. That might be `TokenTextSplitter` but I think I recall seeing that is just an alias for `SentenceSplitter`. Either way, both are documented to respect `chunk_size` so its unclear (so far) where the bug is for epub.

**Comment by jimlloyd** [comment]
There is a pretty harsh restriction imposed by the fact that sentence embeddings are limited to 512 tokens with most of the available open source embeddings models. 

@cpacker do you have a concise term that maps to the concept of a virtual memory page size? Virtual memory is paged between the VM persistent store and RAM in chunks of (usually) 4K bytes. Currently we are limited to a "page size" of 300 tokens, right? Correct me if I am wrong, but you probably have been using a page size of 300 tokens because of the 512 token limitation for embeddings? If the 300 token limit is a soft limit, but the 512 token limit is a hard limit, then it makes sense to set the soft limit well under the hard limit.

I think we should be assuming that by the end of 2024 we will have models that work well with context windows of 100K tokens or more. I saw recently that Sam Altman said they will support context up to 1M tokens. We are limited to ~16K context now because the big O computational cost is O(N^2), but there is active research into O(N) methods. When you consider that 1M is just 1K^2 it is totally reasonable that 1M will be achievable if good O(N) methods become available.

If we can have context windows larger than 16K then the memgpt architecture will become more powerful by increasing the 300 token page size to say 1K tokens. But we can't do that until we find a way to get beyond the 512 token limit for sentence embeddings.

I am not familiar with the space of possible embedding models but am trying to understand it better. For example, I believe there is an embeddings API that is accessible with llama.cpp (and probably other backends) that uses the LLM's own embeddings model. I wonder if these models use a higher limit?

Anyway, this comment went out on to a tangent, but I think this bug will be hard to fix until one of two things happens:

1. We figure out how to get llama-index to make its node chunking only use token length considerations, and to strictly honor the upper bound that we set. If we had this then we just need to set the upper bound to 500 tokens so that we never request an embedding for more than the 512 token hard limit.
2. We find and support an embeddings model that works well with a larger limit. Even a 1024 token limit while leaving everything else as is would effectively fix this bug.

**Comment by jimlloyd** [comment]
I just created a llama-index issue: https://github.com/run-llama/llama_index/issues/9820

**Comment by jimlloyd** [comment]
Note to self:
https://stackoverflow.com/questions/75901231/max-seq-length-for-transformer-sentence-bert
"When text is long and contains more than 512 tokens, it does not throw an exception. I assume it automatically truncates the input to 512 tokens." Using this would be an ugly hack, so other methods are preferable.

**Comment by jimlloyd** [comment]
Another link that may be useful: https://www.sbert.net/examples/applications/computing-embeddings/README.html

**Comment by jimlloyd** [comment]
@cpacker there are several embeddings models on the [MTEB](https://huggingface.co/spaces/mteb/leaderboard) that appear to have max sequence length >= 768 and are relatively small (e.g < 1Gb). I have tried out several of them with `text-embedding-inference` and the all fail to load due to what I think are trivial little configuration errors. The config.json files are missing parameters such as `max_position_embeddings` or `pad_token_id`. I have reached out to one of the authors but I think perhaps I should just fork the repo, apply a fix, and then see if we can get the model to load. This would be my first time working with hugging face repos. I think I see what the process is, but if I understand the errors I am getting I may need to create an organization. Or use the memgpt organization. Can you add me that org? I am https://huggingface.co/jimlloyd

**Comment by jimlloyd** [comment]
One of the authors of the models on MTEB with max seq length >= 768 responded in a way that makes it seem he is not interested in updating the configuration of the model, but he stated: "I usually just truncate the sequence to 512 tokens -- that works well enough."

So, I am figuring out how to do that in our loading code and I think I can make it work for our `local` embedding endpoint. It will be more work to do it for the other embedding endpoint types.

I should be able to have a PR today.

**Comment by sarahwooders** [comment]
#1098
