### ISSUE TITLE
Design a new architecture to support future models

### ISSUE THREAD

**Issue by bitsnaps** [cpacker/MemGPT#776]
**Describtion the bug**
I've been trying different models, then I discovered that most of non-supported models end with the error:
```
    raise LocalLLMError(f"Got back an empty response string from {endpoint}")
memgpt.errors.LocalLLMError: Got back an empty response string from http://localhost:5000
WARNING: your terminal doesn't support cursor position requests (CPR).
```
Although the endpoint `http://localhost:5000` works perfectly in the same environnement with python/autogen/cURL...etc.

I believe the current architecture is the cause of all these error, since it relies on the model chat wrapper to parse the output, which need to tweak/update MemGPT for every LLM... this issue is not related to a specific model. Wouldn't be better to design an open architecture/standard to extend the compatibility with future (e.g. REST API, abstract interface/layer, adapter pattern...etc.)? If this is hard to achieve because of the variety of the current models, can we group them in categories (e.g. GPTQ, GUFF, Llama-based, openai compatible...etc.) ?

P.S. Trying to isolate MemGPT at the installation (running on a different `venv`) didn't make any better so far.

** Describe of setup**

- [X ] MemGPT version
  - The latest one at the moment.
  
- [X ] How did you install memgpt?
  - Using: `pip install pymemgpt`
- [X ] Describe your setup
  - Google's Colab with GPU T4.
  - Running `memgpt` on a `xterm`.

**Additional context**
All the models are working with `openai` compatible API using python, and works with [autogen](https://github.com/microsoft/autogen) framework.

**Local LLM details**

- [ X] Multiple models tried: `TheBloke_SOLAR-10.7B-Instruct-v1.0-GGUF`, `dolphin-2.6-mixtral-8x7b-GPTQ`...
- [X ] The local LLM backend: `webui`
- [X ] The hardware for the local LLM backend: Google's Colab with GPU.

**Comment by cpacker** [comment]
The "open architecture" you're describing is basically just `completions` APIs. If every LLM backend supported `completions` APIs the same way (eg the OpenAI reference), then there would be no need to write extra code for eg ollama, lmstudio, etc. However that's not the case, which is why we need extra code.

However, if you or anyone else *does* create a backend that supports completions, then you can just use `webui` as the backend type in MemGPT and it'll work.

The chat wrapper is a separate issue - basically that boils down to function calling and performance. If the backend support completions **with function calling**, then MemGPT can just treat it as a `chat/completions` endpoint - ie just select `openai` as the backend type in MemGPT and it'll work. However, there are many implementation details that go into doing function calling well, and IMO the only API service that does it well right now is OpenAI/Azure. When the backend doesn't do function calling well, you're much better off using the raw `completions` API and writing your own function calling parsers, which is the idea behind MemGPT using `completions` with "wrappers".

Hopefully a year from now there will be standardized prompt formats and standardized prompt formats / output formats to function calling, but until then, we need to do this to make things perform decently when not using OpenAI API.
