### ISSUE TITLE
Agent seems to be getting stuck in a perpetual 'motivational' state, in its thought stage (GPT4)

### ISSUE THREAD

**Issue by aforamenta** [cpacker/MemGPT#81]
Anyone else noticed this before?

I was very harsh on purpose with the agent, being seemingly keen on how i wanted the agent to act human and make up information. It was persistent on not doing so and I kept insisting. When I load the information that was /saved, no matter what I say, it always gets stuck in a motivational loop as if reassuring itself of its capabilities.

This makes it take toooo long and sometimes it does not even reply.

Images attached related:

![image](https://github.com/cpacker/MemGPT/assets/3923322/260f2254-087e-4720-ba27-67a3fa250706)
![image](https://github.com/cpacker/MemGPT/assets/3923322/8cad9e9a-470c-4121-856c-80c7c1ebeb9d)
![image](https://github.com/cpacker/MemGPT/assets/3923322/ac819beb-6a44-4305-a331-09d937ba1426)

**Comment by cpacker** [comment]
Sometimes LLMs can go off the rails. 

One way to try and correct it is to say in your message something along the lines of "_You are looping in a motivational state. Remember to keep your inner thoughts less than 200 characters at all times._".

Another (preemptive) way to try and fix this issue if you notice it a lot is to put inside the persona "_Your inner thoughts are very short and have few words_".

A third approach is to try and "course correct" the agent by manually editing the messages it has sent (ie rewriting history). I will try to merge in a feature where you can edit the LLMs output (#218) ASAP to allow this easily through the CLI.

Closing for now because there's no clear fix for this other than the above solutions.
