### ISSUE TITLE
0.2.12: If embeddings dimensions changes then must start with new DB

### ISSUE THREAD

**Issue by jimlloyd** [cpacker/MemGPT#814]
**Describe the bug**

We currently have just one table `memgpt_archival_memory_agent` and one table `memgpt_passages`. I believe `memgpt_archival_memory_agent` is created first, maybe immediately after `memgpt configure` or perhaps when the first agent is created. `memgpt_passages` is created later, possibly on the first `/attach`. In my case, I started with the intention to use hugging-face embeddings served locally with 1024 dimensions, but due to #811 I was forced to switch to local embeddings with 384 dimensions. I was able to successfully create load a lot of passages from a recursive directory load, all of which had dimensions 384. But when I tried to attach to that data source I got an error `psycopg2.errors.DataException: expected 1024 dimensions, not 384`.
It might be possible to fix this more dynamically, i.e. be slash commands, but that should probably be low priority until there is more evidence that this is a common problem. It *might* indicate that we want a more flexible schema.

Note that everytime I an forced to create a new DB I have to do a long `directory load ...` so it is annoying.

**Please describe your setup**

- [ ] MemGPT version
0.2.12

- [ ] How did you install memgpt?
poetry

- [ ] Describe your setup
MacOS Sonoma & terminal in VS Code.

**Screenshots**
N/A

**Additional context**
N/A

---

If you're not using OpenAI, please provide additional information on your local LLM setup:

**Local LLM details**

If you are trying to run MemGPT with local LLMs, please provide the following information:

- [ ] The exact model you're trying to use (e.g. `dolphin-2.1-mistral-7b.Q6_K.gguf`)
- [ ] The local LLM backend you are using (web UI? LM Studio?)
- [ ] Your hardware for the local LLM backend (local computer? operating system? remote RunPod?)

**Comment by sarahwooders** [comment]
Unfortunately this is an issue postgres, as we have to pre-define the dimensionality of the embedding column (e.g. with `Vector(1024)`. One idea we have to solve this problem is to zero-pad the vectors to a fixed maximum sized  (e.g. `Vector(4096)`) so that any size vector can be stored in that column. 

If we do this, we'll need to make sure that whenever we run a vector query, we check to make sure the query vector and embedding vectors are compatible (by ensuring the embeddings were computed with the same model).

**Comment by sarahwooders** [comment]
This should be solved by #852
